### PR TITLE
Haproxy 2.2

### PR DESCRIPTION
**Pull request by todeveni**

### CODE REVIEW

**Comment by tobybellwood** [comment]
Thanks @todeveni I'll check this out!

**Comment by todeveni** [comment]
Thanks @tobybellwood 

I've been running this since july without problems with `docker build -t amazeeio/haproxy .` before starting pygmy.

**Comment by tobybellwood** [comment]
This repo hasn't been on my radar for ages, so missed @fubarhouse doing similar in #6.  Will go through the other issues/PRs too

**Comment by fubarhouse** [comment]
Just tested this in `pygmy-go` and it's all good.
Routes are resolving and versions are as expected.

**Pull request closed without merging**
